// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AXSCMDABORTDATA_MOTION_CORE_FBTYPES_H_
#define FLATBUFFERS_GENERATED_AXSCMDABORTDATA_MOTION_CORE_FBTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace motion {
namespace core {
namespace fbtypes {

struct AxsCmdAbortData;
struct AxsCmdAbortDataBuilder;
struct AxsCmdAbortDataT;

bool operator==(const AxsCmdAbortDataT &lhs, const AxsCmdAbortDataT &rhs);
bool operator!=(const AxsCmdAbortDataT &lhs, const AxsCmdAbortDataT &rhs);

struct AxsCmdAbortDataT : public ::flatbuffers::NativeTable {
  typedef AxsCmdAbortData TableType;
  double dec = 1.0;
  double jrkDec = 0.0;
};

/// parameters of the axis abort command
struct AxsCmdAbortData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AxsCmdAbortDataT NativeTableType;
  typedef AxsCmdAbortDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEC = 4,
    VT_JRKDEC = 6
  };
  /// commanded deceleration limit (must be a positive value)
  double dec() const {
    return GetField<double>(VT_DEC, 1.0);
  }
  /// commanded deceleration jerk limit (must be a positive value OR zero), zero means "not jerk limited"
  double jrkDec() const {
    return GetField<double>(VT_JRKDEC, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_DEC, 8) &&
           VerifyField<double>(verifier, VT_JRKDEC, 8) &&
           verifier.EndTable();
  }
  AxsCmdAbortDataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AxsCmdAbortDataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AxsCmdAbortData> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdAbortDataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AxsCmdAbortDataBuilder {
  typedef AxsCmdAbortData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dec(double dec) {
    fbb_.AddElement<double>(AxsCmdAbortData::VT_DEC, dec, 1.0);
  }
  void add_jrkDec(double jrkDec) {
    fbb_.AddElement<double>(AxsCmdAbortData::VT_JRKDEC, jrkDec, 0.0);
  }
  explicit AxsCmdAbortDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AxsCmdAbortData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AxsCmdAbortData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AxsCmdAbortData> CreateAxsCmdAbortData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double dec = 1.0,
    double jrkDec = 0.0) {
  AxsCmdAbortDataBuilder builder_(_fbb);
  builder_.add_jrkDec(jrkDec);
  builder_.add_dec(dec);
  return builder_.Finish();
}

::flatbuffers::Offset<AxsCmdAbortData> CreateAxsCmdAbortData(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdAbortDataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const AxsCmdAbortDataT &lhs, const AxsCmdAbortDataT &rhs) {
  return
      (lhs.dec == rhs.dec) &&
      (lhs.jrkDec == rhs.jrkDec);
}

inline bool operator!=(const AxsCmdAbortDataT &lhs, const AxsCmdAbortDataT &rhs) {
    return !(lhs == rhs);
}


inline AxsCmdAbortDataT *AxsCmdAbortData::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AxsCmdAbortDataT>(new AxsCmdAbortDataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AxsCmdAbortData::UnPackTo(AxsCmdAbortDataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dec(); _o->dec = _e; }
  { auto _e = jrkDec(); _o->jrkDec = _e; }
}

inline ::flatbuffers::Offset<AxsCmdAbortData> AxsCmdAbortData::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdAbortDataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAxsCmdAbortData(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AxsCmdAbortData> CreateAxsCmdAbortData(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdAbortDataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AxsCmdAbortDataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dec = _o->dec;
  auto _jrkDec = _o->jrkDec;
  return motion::core::fbtypes::CreateAxsCmdAbortData(
      _fbb,
      _dec,
      _jrkDec);
}

inline const motion::core::fbtypes::AxsCmdAbortData *GetAxsCmdAbortData(const void *buf) {
  return ::flatbuffers::GetRoot<motion::core::fbtypes::AxsCmdAbortData>(buf);
}

inline const motion::core::fbtypes::AxsCmdAbortData *GetSizePrefixedAxsCmdAbortData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<motion::core::fbtypes::AxsCmdAbortData>(buf);
}

inline bool VerifyAxsCmdAbortDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<motion::core::fbtypes::AxsCmdAbortData>(nullptr);
}

inline bool VerifySizePrefixedAxsCmdAbortDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<motion::core::fbtypes::AxsCmdAbortData>(nullptr);
}

inline void FinishAxsCmdAbortDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsCmdAbortData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAxsCmdAbortDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsCmdAbortData> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<motion::core::fbtypes::AxsCmdAbortDataT> UnPackAxsCmdAbortData(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsCmdAbortDataT>(GetAxsCmdAbortData(buf)->UnPack(res));
}

inline std::unique_ptr<motion::core::fbtypes::AxsCmdAbortDataT> UnPackSizePrefixedAxsCmdAbortData(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsCmdAbortDataT>(GetSizePrefixedAxsCmdAbortData(buf)->UnPack(res));
}

}  // namespace fbtypes
}  // namespace core
}  // namespace motion

#endif  // FLATBUFFERS_GENERATED_AXSCMDABORTDATA_MOTION_CORE_FBTYPES_H_
