// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AXSCMDPOSDATA_MOTION_CORE_FBTYPES_H_
#define FLATBUFFERS_GENERATED_AXSCMDPOSDATA_MOTION_CORE_FBTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "dynamicLimits_generated.h"

namespace motion {
namespace core {
namespace fbtypes {

struct AxsCmdPosData;
struct AxsCmdPosDataBuilder;
struct AxsCmdPosDataT;

bool operator==(const AxsCmdPosDataT &lhs, const AxsCmdPosDataT &rhs);
bool operator!=(const AxsCmdPosDataT &lhs, const AxsCmdPosDataT &rhs);

/// Selected direction for PosAbs with modulo axis
enum CmdPosAbsDir : int8_t {
  /// use shortest way to reach target position
  CmdPosAbsDir_SHORTEST_WAY = 0,
  /// move only in positive direction to reach target position
  CmdPosAbsDir_POSITIVE_DIR = 1,
  /// move only in negative direction to reach target position
  CmdPosAbsDir_NEGATIVE_DIR = 2,
  /// when currently moving: continue to move in this direction to reach target position; 
  /// when in stand still: use SHORTEST_WAY
  CmdPosAbsDir_CURRENT_DIR = 3,
  CmdPosAbsDir_MIN = CmdPosAbsDir_SHORTEST_WAY,
  CmdPosAbsDir_MAX = CmdPosAbsDir_CURRENT_DIR
};

inline const CmdPosAbsDir (&EnumValuesCmdPosAbsDir())[4] {
  static const CmdPosAbsDir values[] = {
    CmdPosAbsDir_SHORTEST_WAY,
    CmdPosAbsDir_POSITIVE_DIR,
    CmdPosAbsDir_NEGATIVE_DIR,
    CmdPosAbsDir_CURRENT_DIR
  };
  return values;
}

inline const char * const *EnumNamesCmdPosAbsDir() {
  static const char * const names[5] = {
    "SHORTEST_WAY",
    "POSITIVE_DIR",
    "NEGATIVE_DIR",
    "CURRENT_DIR",
    nullptr
  };
  return names;
}

inline const char *EnumNameCmdPosAbsDir(CmdPosAbsDir e) {
  if (::flatbuffers::IsOutRange(e, CmdPosAbsDir_SHORTEST_WAY, CmdPosAbsDir_CURRENT_DIR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCmdPosAbsDir()[index];
}

struct AxsCmdPosDataT : public ::flatbuffers::NativeTable {
  typedef AxsCmdPosData TableType;
  double axsPos = 0.0;
  bool buffered = true;
  std::unique_ptr<motion::core::fbtypes::DynamicLimitsT> lim{};
  motion::core::fbtypes::CmdPosAbsDir direction = motion::core::fbtypes::CmdPosAbsDir_SHORTEST_WAY;
  AxsCmdPosDataT() = default;
  AxsCmdPosDataT(const AxsCmdPosDataT &o);
  AxsCmdPosDataT(AxsCmdPosDataT&&) FLATBUFFERS_NOEXCEPT = default;
  AxsCmdPosDataT &operator=(AxsCmdPosDataT o) FLATBUFFERS_NOEXCEPT;
};

/// parameters of the axis position commands
struct AxsCmdPosData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AxsCmdPosDataT NativeTableType;
  typedef AxsCmdPosDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AXSPOS = 4,
    VT_BUFFERED = 6,
    VT_LIM = 8,
    VT_DIRECTION = 10
  };
  /// commanded target position (or increment for relative position command)
  double axsPos() const {
    return GetField<double>(VT_AXSPOS, 0.0);
  }
  /// should this be a buffered command?
  bool buffered() const {
    return GetField<uint8_t>(VT_BUFFERED, 1) != 0;
  }
  /// dynamic limits for the motion of this command
  const motion::core::fbtypes::DynamicLimits *lim() const {
    return GetPointer<const motion::core::fbtypes::DynamicLimits *>(VT_LIM);
  }
  /// Selected direction for PosAbs with modulo axis (ignored in all other cases)
  motion::core::fbtypes::CmdPosAbsDir direction() const {
    return static_cast<motion::core::fbtypes::CmdPosAbsDir>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_AXSPOS, 8) &&
           VerifyField<uint8_t>(verifier, VT_BUFFERED, 1) &&
           VerifyOffset(verifier, VT_LIM) &&
           verifier.VerifyTable(lim()) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           verifier.EndTable();
  }
  AxsCmdPosDataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AxsCmdPosDataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AxsCmdPosData> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdPosDataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AxsCmdPosDataBuilder {
  typedef AxsCmdPosData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_axsPos(double axsPos) {
    fbb_.AddElement<double>(AxsCmdPosData::VT_AXSPOS, axsPos, 0.0);
  }
  void add_buffered(bool buffered) {
    fbb_.AddElement<uint8_t>(AxsCmdPosData::VT_BUFFERED, static_cast<uint8_t>(buffered), 1);
  }
  void add_lim(::flatbuffers::Offset<motion::core::fbtypes::DynamicLimits> lim) {
    fbb_.AddOffset(AxsCmdPosData::VT_LIM, lim);
  }
  void add_direction(motion::core::fbtypes::CmdPosAbsDir direction) {
    fbb_.AddElement<int8_t>(AxsCmdPosData::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  explicit AxsCmdPosDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AxsCmdPosData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AxsCmdPosData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AxsCmdPosData> CreateAxsCmdPosData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double axsPos = 0.0,
    bool buffered = true,
    ::flatbuffers::Offset<motion::core::fbtypes::DynamicLimits> lim = 0,
    motion::core::fbtypes::CmdPosAbsDir direction = motion::core::fbtypes::CmdPosAbsDir_SHORTEST_WAY) {
  AxsCmdPosDataBuilder builder_(_fbb);
  builder_.add_axsPos(axsPos);
  builder_.add_lim(lim);
  builder_.add_direction(direction);
  builder_.add_buffered(buffered);
  return builder_.Finish();
}

::flatbuffers::Offset<AxsCmdPosData> CreateAxsCmdPosData(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdPosDataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const AxsCmdPosDataT &lhs, const AxsCmdPosDataT &rhs) {
  return
      (lhs.axsPos == rhs.axsPos) &&
      (lhs.buffered == rhs.buffered) &&
      ((lhs.lim == rhs.lim) || (lhs.lim && rhs.lim && *lhs.lim == *rhs.lim)) &&
      (lhs.direction == rhs.direction);
}

inline bool operator!=(const AxsCmdPosDataT &lhs, const AxsCmdPosDataT &rhs) {
    return !(lhs == rhs);
}


inline AxsCmdPosDataT::AxsCmdPosDataT(const AxsCmdPosDataT &o)
      : axsPos(o.axsPos),
        buffered(o.buffered),
        lim((o.lim) ? new motion::core::fbtypes::DynamicLimitsT(*o.lim) : nullptr),
        direction(o.direction) {
}

inline AxsCmdPosDataT &AxsCmdPosDataT::operator=(AxsCmdPosDataT o) FLATBUFFERS_NOEXCEPT {
  std::swap(axsPos, o.axsPos);
  std::swap(buffered, o.buffered);
  std::swap(lim, o.lim);
  std::swap(direction, o.direction);
  return *this;
}

inline AxsCmdPosDataT *AxsCmdPosData::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AxsCmdPosDataT>(new AxsCmdPosDataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AxsCmdPosData::UnPackTo(AxsCmdPosDataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = axsPos(); _o->axsPos = _e; }
  { auto _e = buffered(); _o->buffered = _e; }
  { auto _e = lim(); if (_e) { if(_o->lim) { _e->UnPackTo(_o->lim.get(), _resolver); } else { _o->lim = std::unique_ptr<motion::core::fbtypes::DynamicLimitsT>(_e->UnPack(_resolver)); } } else if (_o->lim) { _o->lim.reset(); } }
  { auto _e = direction(); _o->direction = _e; }
}

inline ::flatbuffers::Offset<AxsCmdPosData> AxsCmdPosData::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdPosDataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAxsCmdPosData(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AxsCmdPosData> CreateAxsCmdPosData(::flatbuffers::FlatBufferBuilder &_fbb, const AxsCmdPosDataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AxsCmdPosDataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _axsPos = _o->axsPos;
  auto _buffered = _o->buffered;
  auto _lim = _o->lim ? CreateDynamicLimits(_fbb, _o->lim.get(), _rehasher) : 0;
  auto _direction = _o->direction;
  return motion::core::fbtypes::CreateAxsCmdPosData(
      _fbb,
      _axsPos,
      _buffered,
      _lim,
      _direction);
}

inline const motion::core::fbtypes::AxsCmdPosData *GetAxsCmdPosData(const void *buf) {
  return ::flatbuffers::GetRoot<motion::core::fbtypes::AxsCmdPosData>(buf);
}

inline const motion::core::fbtypes::AxsCmdPosData *GetSizePrefixedAxsCmdPosData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<motion::core::fbtypes::AxsCmdPosData>(buf);
}

inline bool VerifyAxsCmdPosDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<motion::core::fbtypes::AxsCmdPosData>(nullptr);
}

inline bool VerifySizePrefixedAxsCmdPosDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<motion::core::fbtypes::AxsCmdPosData>(nullptr);
}

inline void FinishAxsCmdPosDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsCmdPosData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAxsCmdPosDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsCmdPosData> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<motion::core::fbtypes::AxsCmdPosDataT> UnPackAxsCmdPosData(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsCmdPosDataT>(GetAxsCmdPosData(buf)->UnPack(res));
}

inline std::unique_ptr<motion::core::fbtypes::AxsCmdPosDataT> UnPackSizePrefixedAxsCmdPosData(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsCmdPosDataT>(GetSizePrefixedAxsCmdPosData(buf)->UnPack(res));
}

}  // namespace fbtypes
}  // namespace core
}  // namespace motion

#endif  // FLATBUFFERS_GENERATED_AXSCMDPOSDATA_MOTION_CORE_FBTYPES_H_
