// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AXSIPOVALUES_MOTION_CORE_FBTYPES_H_
#define FLATBUFFERS_GENERATED_AXSIPOVALUES_MOTION_CORE_FBTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace motion {
namespace core {
namespace fbtypes {

struct AxsIpoValues;
struct AxsIpoValuesBuilder;
struct AxsIpoValuesT;

bool operator==(const AxsIpoValuesT &lhs, const AxsIpoValuesT &rhs);
bool operator!=(const AxsIpoValuesT &lhs, const AxsIpoValuesT &rhs);

struct AxsIpoValuesT : public ::flatbuffers::NativeTable {
  typedef AxsIpoValues TableType;
  double ipoPos = 0.0;
  double ipoVel = 0.0;
  double ipoAcc = 0.0;
  double ipoJrk = 0.0;
  std::string ipoPosUnit{};
  std::string ipoVelUnit{};
  std::string ipoAccUnit{};
  std::string ipoJrkUnit{};
  std::string ipoTrqUnit{};
  double ipoTrq = 0.0;
};

/// currently interpolated values
struct AxsIpoValues FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AxsIpoValuesT NativeTableType;
  typedef AxsIpoValuesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IPOPOS = 4,
    VT_IPOVEL = 6,
    VT_IPOACC = 8,
    VT_IPOJRK = 10,
    VT_IPOPOSUNIT = 12,
    VT_IPOVELUNIT = 14,
    VT_IPOACCUNIT = 16,
    VT_IPOJRKUNIT = 18,
    VT_IPOTRQUNIT = 20,
    VT_IPOTRQ = 22
  };
  /// currently interpolated position
  double ipoPos() const {
    return GetField<double>(VT_IPOPOS, 0.0);
  }
  /// currently interpolated velocity
  double ipoVel() const {
    return GetField<double>(VT_IPOVEL, 0.0);
  }
  /// currently interpolated acceleration
  double ipoAcc() const {
    return GetField<double>(VT_IPOACC, 0.0);
  }
  /// currently interpolated jerk
  double ipoJrk() const {
    return GetField<double>(VT_IPOJRK, 0.0);
  }
  /// unit of currently interpolated position
  const ::flatbuffers::String *ipoPosUnit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPOPOSUNIT);
  }
  /// unit of currently interpolated velocity
  const ::flatbuffers::String *ipoVelUnit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPOVELUNIT);
  }
  /// unit of currently interpolated acceleration
  const ::flatbuffers::String *ipoAccUnit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPOACCUNIT);
  }
  /// unit of currently interpolated jerk
  const ::flatbuffers::String *ipoJrkUnit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPOJRKUNIT);
  }
  /// unit of currently interpolated torque
  const ::flatbuffers::String *ipoTrqUnit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPOTRQUNIT);
  }
  /// currently interpolated torque
  double ipoTrq() const {
    return GetField<double>(VT_IPOTRQ, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_IPOPOS, 8) &&
           VerifyField<double>(verifier, VT_IPOVEL, 8) &&
           VerifyField<double>(verifier, VT_IPOACC, 8) &&
           VerifyField<double>(verifier, VT_IPOJRK, 8) &&
           VerifyOffset(verifier, VT_IPOPOSUNIT) &&
           verifier.VerifyString(ipoPosUnit()) &&
           VerifyOffset(verifier, VT_IPOVELUNIT) &&
           verifier.VerifyString(ipoVelUnit()) &&
           VerifyOffset(verifier, VT_IPOACCUNIT) &&
           verifier.VerifyString(ipoAccUnit()) &&
           VerifyOffset(verifier, VT_IPOJRKUNIT) &&
           verifier.VerifyString(ipoJrkUnit()) &&
           VerifyOffset(verifier, VT_IPOTRQUNIT) &&
           verifier.VerifyString(ipoTrqUnit()) &&
           VerifyField<double>(verifier, VT_IPOTRQ, 8) &&
           verifier.EndTable();
  }
  AxsIpoValuesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AxsIpoValuesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AxsIpoValues> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsIpoValuesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AxsIpoValuesBuilder {
  typedef AxsIpoValues Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ipoPos(double ipoPos) {
    fbb_.AddElement<double>(AxsIpoValues::VT_IPOPOS, ipoPos, 0.0);
  }
  void add_ipoVel(double ipoVel) {
    fbb_.AddElement<double>(AxsIpoValues::VT_IPOVEL, ipoVel, 0.0);
  }
  void add_ipoAcc(double ipoAcc) {
    fbb_.AddElement<double>(AxsIpoValues::VT_IPOACC, ipoAcc, 0.0);
  }
  void add_ipoJrk(double ipoJrk) {
    fbb_.AddElement<double>(AxsIpoValues::VT_IPOJRK, ipoJrk, 0.0);
  }
  void add_ipoPosUnit(::flatbuffers::Offset<::flatbuffers::String> ipoPosUnit) {
    fbb_.AddOffset(AxsIpoValues::VT_IPOPOSUNIT, ipoPosUnit);
  }
  void add_ipoVelUnit(::flatbuffers::Offset<::flatbuffers::String> ipoVelUnit) {
    fbb_.AddOffset(AxsIpoValues::VT_IPOVELUNIT, ipoVelUnit);
  }
  void add_ipoAccUnit(::flatbuffers::Offset<::flatbuffers::String> ipoAccUnit) {
    fbb_.AddOffset(AxsIpoValues::VT_IPOACCUNIT, ipoAccUnit);
  }
  void add_ipoJrkUnit(::flatbuffers::Offset<::flatbuffers::String> ipoJrkUnit) {
    fbb_.AddOffset(AxsIpoValues::VT_IPOJRKUNIT, ipoJrkUnit);
  }
  void add_ipoTrqUnit(::flatbuffers::Offset<::flatbuffers::String> ipoTrqUnit) {
    fbb_.AddOffset(AxsIpoValues::VT_IPOTRQUNIT, ipoTrqUnit);
  }
  void add_ipoTrq(double ipoTrq) {
    fbb_.AddElement<double>(AxsIpoValues::VT_IPOTRQ, ipoTrq, 0.0);
  }
  explicit AxsIpoValuesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AxsIpoValues> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AxsIpoValues>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AxsIpoValues> CreateAxsIpoValues(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double ipoPos = 0.0,
    double ipoVel = 0.0,
    double ipoAcc = 0.0,
    double ipoJrk = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> ipoPosUnit = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ipoVelUnit = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ipoAccUnit = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ipoJrkUnit = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ipoTrqUnit = 0,
    double ipoTrq = 0.0) {
  AxsIpoValuesBuilder builder_(_fbb);
  builder_.add_ipoTrq(ipoTrq);
  builder_.add_ipoJrk(ipoJrk);
  builder_.add_ipoAcc(ipoAcc);
  builder_.add_ipoVel(ipoVel);
  builder_.add_ipoPos(ipoPos);
  builder_.add_ipoTrqUnit(ipoTrqUnit);
  builder_.add_ipoJrkUnit(ipoJrkUnit);
  builder_.add_ipoAccUnit(ipoAccUnit);
  builder_.add_ipoVelUnit(ipoVelUnit);
  builder_.add_ipoPosUnit(ipoPosUnit);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AxsIpoValues> CreateAxsIpoValuesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double ipoPos = 0.0,
    double ipoVel = 0.0,
    double ipoAcc = 0.0,
    double ipoJrk = 0.0,
    const char *ipoPosUnit = nullptr,
    const char *ipoVelUnit = nullptr,
    const char *ipoAccUnit = nullptr,
    const char *ipoJrkUnit = nullptr,
    const char *ipoTrqUnit = nullptr,
    double ipoTrq = 0.0) {
  auto ipoPosUnit__ = ipoPosUnit ? _fbb.CreateString(ipoPosUnit) : 0;
  auto ipoVelUnit__ = ipoVelUnit ? _fbb.CreateString(ipoVelUnit) : 0;
  auto ipoAccUnit__ = ipoAccUnit ? _fbb.CreateString(ipoAccUnit) : 0;
  auto ipoJrkUnit__ = ipoJrkUnit ? _fbb.CreateString(ipoJrkUnit) : 0;
  auto ipoTrqUnit__ = ipoTrqUnit ? _fbb.CreateString(ipoTrqUnit) : 0;
  return motion::core::fbtypes::CreateAxsIpoValues(
      _fbb,
      ipoPos,
      ipoVel,
      ipoAcc,
      ipoJrk,
      ipoPosUnit__,
      ipoVelUnit__,
      ipoAccUnit__,
      ipoJrkUnit__,
      ipoTrqUnit__,
      ipoTrq);
}

::flatbuffers::Offset<AxsIpoValues> CreateAxsIpoValues(::flatbuffers::FlatBufferBuilder &_fbb, const AxsIpoValuesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const AxsIpoValuesT &lhs, const AxsIpoValuesT &rhs) {
  return
      (lhs.ipoPos == rhs.ipoPos) &&
      (lhs.ipoVel == rhs.ipoVel) &&
      (lhs.ipoAcc == rhs.ipoAcc) &&
      (lhs.ipoJrk == rhs.ipoJrk) &&
      (lhs.ipoPosUnit == rhs.ipoPosUnit) &&
      (lhs.ipoVelUnit == rhs.ipoVelUnit) &&
      (lhs.ipoAccUnit == rhs.ipoAccUnit) &&
      (lhs.ipoJrkUnit == rhs.ipoJrkUnit) &&
      (lhs.ipoTrqUnit == rhs.ipoTrqUnit) &&
      (lhs.ipoTrq == rhs.ipoTrq);
}

inline bool operator!=(const AxsIpoValuesT &lhs, const AxsIpoValuesT &rhs) {
    return !(lhs == rhs);
}


inline AxsIpoValuesT *AxsIpoValues::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AxsIpoValuesT>(new AxsIpoValuesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AxsIpoValues::UnPackTo(AxsIpoValuesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ipoPos(); _o->ipoPos = _e; }
  { auto _e = ipoVel(); _o->ipoVel = _e; }
  { auto _e = ipoAcc(); _o->ipoAcc = _e; }
  { auto _e = ipoJrk(); _o->ipoJrk = _e; }
  { auto _e = ipoPosUnit(); if (_e) _o->ipoPosUnit = _e->str(); }
  { auto _e = ipoVelUnit(); if (_e) _o->ipoVelUnit = _e->str(); }
  { auto _e = ipoAccUnit(); if (_e) _o->ipoAccUnit = _e->str(); }
  { auto _e = ipoJrkUnit(); if (_e) _o->ipoJrkUnit = _e->str(); }
  { auto _e = ipoTrqUnit(); if (_e) _o->ipoTrqUnit = _e->str(); }
  { auto _e = ipoTrq(); _o->ipoTrq = _e; }
}

inline ::flatbuffers::Offset<AxsIpoValues> AxsIpoValues::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AxsIpoValuesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAxsIpoValues(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AxsIpoValues> CreateAxsIpoValues(::flatbuffers::FlatBufferBuilder &_fbb, const AxsIpoValuesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AxsIpoValuesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ipoPos = _o->ipoPos;
  auto _ipoVel = _o->ipoVel;
  auto _ipoAcc = _o->ipoAcc;
  auto _ipoJrk = _o->ipoJrk;
  auto _ipoPosUnit = _o->ipoPosUnit.empty() ? 0 : _fbb.CreateString(_o->ipoPosUnit);
  auto _ipoVelUnit = _o->ipoVelUnit.empty() ? 0 : _fbb.CreateString(_o->ipoVelUnit);
  auto _ipoAccUnit = _o->ipoAccUnit.empty() ? 0 : _fbb.CreateString(_o->ipoAccUnit);
  auto _ipoJrkUnit = _o->ipoJrkUnit.empty() ? 0 : _fbb.CreateString(_o->ipoJrkUnit);
  auto _ipoTrqUnit = _o->ipoTrqUnit.empty() ? 0 : _fbb.CreateString(_o->ipoTrqUnit);
  auto _ipoTrq = _o->ipoTrq;
  return motion::core::fbtypes::CreateAxsIpoValues(
      _fbb,
      _ipoPos,
      _ipoVel,
      _ipoAcc,
      _ipoJrk,
      _ipoPosUnit,
      _ipoVelUnit,
      _ipoAccUnit,
      _ipoJrkUnit,
      _ipoTrqUnit,
      _ipoTrq);
}

inline const motion::core::fbtypes::AxsIpoValues *GetAxsIpoValues(const void *buf) {
  return ::flatbuffers::GetRoot<motion::core::fbtypes::AxsIpoValues>(buf);
}

inline const motion::core::fbtypes::AxsIpoValues *GetSizePrefixedAxsIpoValues(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<motion::core::fbtypes::AxsIpoValues>(buf);
}

inline bool VerifyAxsIpoValuesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<motion::core::fbtypes::AxsIpoValues>(nullptr);
}

inline bool VerifySizePrefixedAxsIpoValuesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<motion::core::fbtypes::AxsIpoValues>(nullptr);
}

inline void FinishAxsIpoValuesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsIpoValues> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAxsIpoValuesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::AxsIpoValues> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<motion::core::fbtypes::AxsIpoValuesT> UnPackAxsIpoValues(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsIpoValuesT>(GetAxsIpoValues(buf)->UnPack(res));
}

inline std::unique_ptr<motion::core::fbtypes::AxsIpoValuesT> UnPackSizePrefixedAxsIpoValues(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::AxsIpoValuesT>(GetSizePrefixedAxsIpoValues(buf)->UnPack(res));
}

}  // namespace fbtypes
}  // namespace core
}  // namespace motion

#endif  // FLATBUFFERS_GENERATED_AXSIPOVALUES_MOTION_CORE_FBTYPES_H_
