// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DYNAMICLIMITS_MOTION_CORE_FBTYPES_H_
#define FLATBUFFERS_GENERATED_DYNAMICLIMITS_MOTION_CORE_FBTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace motion {
namespace core {
namespace fbtypes {

struct DynamicLimits;
struct DynamicLimitsBuilder;
struct DynamicLimitsT;

bool operator==(const DynamicLimitsT &lhs, const DynamicLimitsT &rhs);
bool operator!=(const DynamicLimitsT &lhs, const DynamicLimitsT &rhs);

struct DynamicLimitsT : public ::flatbuffers::NativeTable {
  typedef DynamicLimits TableType;
  double vel = 1.0;
  double acc = 1.0;
  double dec = 1.0;
  double jrkAcc = 0.0;
  double jrkDec = 0.0;
};

/// set of dynamic limits (for commands)
struct DynamicLimits FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DynamicLimitsT NativeTableType;
  typedef DynamicLimitsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VEL = 4,
    VT_ACC = 6,
    VT_DEC = 8,
    VT_JRKACC = 10,
    VT_JRKDEC = 12
  };
  /// velocity limit (must be greater than zero)
  double vel() const {
    return GetField<double>(VT_VEL, 1.0);
  }
  /// acceleration limit (must be greater than zero)
  double acc() const {
    return GetField<double>(VT_ACC, 1.0);
  }
  /// deceleration limit (must be greater than zero)
  double dec() const {
    return GetField<double>(VT_DEC, 1.0);
  }
  /// acceleration jerk limit (must be greater than zero OR zero for not jerk limited motion)
  double jrkAcc() const {
    return GetField<double>(VT_JRKACC, 0.0);
  }
  /// deceleration jerk limit (must be greater than zero OR zero for not jerk limited motion)
  double jrkDec() const {
    return GetField<double>(VT_JRKDEC, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VEL, 8) &&
           VerifyField<double>(verifier, VT_ACC, 8) &&
           VerifyField<double>(verifier, VT_DEC, 8) &&
           VerifyField<double>(verifier, VT_JRKACC, 8) &&
           VerifyField<double>(verifier, VT_JRKDEC, 8) &&
           verifier.EndTable();
  }
  DynamicLimitsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DynamicLimitsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DynamicLimits> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DynamicLimitsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DynamicLimitsBuilder {
  typedef DynamicLimits Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vel(double vel) {
    fbb_.AddElement<double>(DynamicLimits::VT_VEL, vel, 1.0);
  }
  void add_acc(double acc) {
    fbb_.AddElement<double>(DynamicLimits::VT_ACC, acc, 1.0);
  }
  void add_dec(double dec) {
    fbb_.AddElement<double>(DynamicLimits::VT_DEC, dec, 1.0);
  }
  void add_jrkAcc(double jrkAcc) {
    fbb_.AddElement<double>(DynamicLimits::VT_JRKACC, jrkAcc, 0.0);
  }
  void add_jrkDec(double jrkDec) {
    fbb_.AddElement<double>(DynamicLimits::VT_JRKDEC, jrkDec, 0.0);
  }
  explicit DynamicLimitsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DynamicLimits> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DynamicLimits>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DynamicLimits> CreateDynamicLimits(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double vel = 1.0,
    double acc = 1.0,
    double dec = 1.0,
    double jrkAcc = 0.0,
    double jrkDec = 0.0) {
  DynamicLimitsBuilder builder_(_fbb);
  builder_.add_jrkDec(jrkDec);
  builder_.add_jrkAcc(jrkAcc);
  builder_.add_dec(dec);
  builder_.add_acc(acc);
  builder_.add_vel(vel);
  return builder_.Finish();
}

::flatbuffers::Offset<DynamicLimits> CreateDynamicLimits(::flatbuffers::FlatBufferBuilder &_fbb, const DynamicLimitsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const DynamicLimitsT &lhs, const DynamicLimitsT &rhs) {
  return
      (lhs.vel == rhs.vel) &&
      (lhs.acc == rhs.acc) &&
      (lhs.dec == rhs.dec) &&
      (lhs.jrkAcc == rhs.jrkAcc) &&
      (lhs.jrkDec == rhs.jrkDec);
}

inline bool operator!=(const DynamicLimitsT &lhs, const DynamicLimitsT &rhs) {
    return !(lhs == rhs);
}


inline DynamicLimitsT *DynamicLimits::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DynamicLimitsT>(new DynamicLimitsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DynamicLimits::UnPackTo(DynamicLimitsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = vel(); _o->vel = _e; }
  { auto _e = acc(); _o->acc = _e; }
  { auto _e = dec(); _o->dec = _e; }
  { auto _e = jrkAcc(); _o->jrkAcc = _e; }
  { auto _e = jrkDec(); _o->jrkDec = _e; }
}

inline ::flatbuffers::Offset<DynamicLimits> DynamicLimits::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DynamicLimitsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDynamicLimits(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DynamicLimits> CreateDynamicLimits(::flatbuffers::FlatBufferBuilder &_fbb, const DynamicLimitsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DynamicLimitsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _vel = _o->vel;
  auto _acc = _o->acc;
  auto _dec = _o->dec;
  auto _jrkAcc = _o->jrkAcc;
  auto _jrkDec = _o->jrkDec;
  return motion::core::fbtypes::CreateDynamicLimits(
      _fbb,
      _vel,
      _acc,
      _dec,
      _jrkAcc,
      _jrkDec);
}

inline const motion::core::fbtypes::DynamicLimits *GetDynamicLimits(const void *buf) {
  return ::flatbuffers::GetRoot<motion::core::fbtypes::DynamicLimits>(buf);
}

inline const motion::core::fbtypes::DynamicLimits *GetSizePrefixedDynamicLimits(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<motion::core::fbtypes::DynamicLimits>(buf);
}

inline bool VerifyDynamicLimitsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<motion::core::fbtypes::DynamicLimits>(nullptr);
}

inline bool VerifySizePrefixedDynamicLimitsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<motion::core::fbtypes::DynamicLimits>(nullptr);
}

inline void FinishDynamicLimitsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::DynamicLimits> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDynamicLimitsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::DynamicLimits> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<motion::core::fbtypes::DynamicLimitsT> UnPackDynamicLimits(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::DynamicLimitsT>(GetDynamicLimits(buf)->UnPack(res));
}

inline std::unique_ptr<motion::core::fbtypes::DynamicLimitsT> UnPackSizePrefixedDynamicLimits(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::DynamicLimitsT>(GetSizePrefixedDynamicLimits(buf)->UnPack(res));
}

}  // namespace fbtypes
}  // namespace core
}  // namespace motion

#endif  // FLATBUFFERS_GENERATED_DYNAMICLIMITS_MOTION_CORE_FBTYPES_H_
