// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYSCMDRESET_MOTION_CORE_FBTYPES_H_
#define FLATBUFFERS_GENERATED_SYSCMDRESET_MOTION_CORE_FBTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace motion {
namespace core {
namespace fbtypes {

struct SysCmdReset;
struct SysCmdResetBuilder;
struct SysCmdResetT;

bool operator==(const SysCmdResetT &lhs, const SysCmdResetT &rhs);
bool operator!=(const SysCmdResetT &lhs, const SysCmdResetT &rhs);

/// Type of the system reset request
enum SysResetType : int8_t {
  /// reset all motion objects, that are currently in an error state and have their error reaction finished
  SysResetType_ResetAllMotionObjectsWithError = 0,
  /// reset all motion object (not yet supported)
  SysResetType_ResetAllMotionObjects = 1,
  SysResetType_MIN = SysResetType_ResetAllMotionObjectsWithError,
  SysResetType_MAX = SysResetType_ResetAllMotionObjects
};

inline const SysResetType (&EnumValuesSysResetType())[2] {
  static const SysResetType values[] = {
    SysResetType_ResetAllMotionObjectsWithError,
    SysResetType_ResetAllMotionObjects
  };
  return values;
}

inline const char * const *EnumNamesSysResetType() {
  static const char * const names[3] = {
    "ResetAllMotionObjectsWithError",
    "ResetAllMotionObjects",
    nullptr
  };
  return names;
}

inline const char *EnumNameSysResetType(SysResetType e) {
  if (::flatbuffers::IsOutRange(e, SysResetType_ResetAllMotionObjectsWithError, SysResetType_ResetAllMotionObjects)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSysResetType()[index];
}

struct SysCmdResetT : public ::flatbuffers::NativeTable {
  typedef SysCmdReset TableType;
  motion::core::fbtypes::SysResetType type = motion::core::fbtypes::SysResetType_ResetAllMotionObjectsWithError;
};

/// request structure for the ResetAllMotionObjects nodes
struct SysCmdReset FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SysCmdResetT NativeTableType;
  typedef SysCmdResetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4
  };
  /// type of the system reset request
  motion::core::fbtypes::SysResetType type() const {
    return static_cast<motion::core::fbtypes::SysResetType>(GetField<int8_t>(VT_TYPE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           verifier.EndTable();
  }
  SysCmdResetT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SysCmdResetT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SysCmdReset> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SysCmdResetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SysCmdResetBuilder {
  typedef SysCmdReset Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(motion::core::fbtypes::SysResetType type) {
    fbb_.AddElement<int8_t>(SysCmdReset::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  explicit SysCmdResetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SysCmdReset> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SysCmdReset>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SysCmdReset> CreateSysCmdReset(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    motion::core::fbtypes::SysResetType type = motion::core::fbtypes::SysResetType_ResetAllMotionObjectsWithError) {
  SysCmdResetBuilder builder_(_fbb);
  builder_.add_type(type);
  return builder_.Finish();
}

::flatbuffers::Offset<SysCmdReset> CreateSysCmdReset(::flatbuffers::FlatBufferBuilder &_fbb, const SysCmdResetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const SysCmdResetT &lhs, const SysCmdResetT &rhs) {
  return
      (lhs.type == rhs.type);
}

inline bool operator!=(const SysCmdResetT &lhs, const SysCmdResetT &rhs) {
    return !(lhs == rhs);
}


inline SysCmdResetT *SysCmdReset::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SysCmdResetT>(new SysCmdResetT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SysCmdReset::UnPackTo(SysCmdResetT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
}

inline ::flatbuffers::Offset<SysCmdReset> SysCmdReset::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SysCmdResetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSysCmdReset(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SysCmdReset> CreateSysCmdReset(::flatbuffers::FlatBufferBuilder &_fbb, const SysCmdResetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SysCmdResetT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  return motion::core::fbtypes::CreateSysCmdReset(
      _fbb,
      _type);
}

inline const motion::core::fbtypes::SysCmdReset *GetSysCmdReset(const void *buf) {
  return ::flatbuffers::GetRoot<motion::core::fbtypes::SysCmdReset>(buf);
}

inline const motion::core::fbtypes::SysCmdReset *GetSizePrefixedSysCmdReset(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<motion::core::fbtypes::SysCmdReset>(buf);
}

inline bool VerifySysCmdResetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<motion::core::fbtypes::SysCmdReset>(nullptr);
}

inline bool VerifySizePrefixedSysCmdResetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<motion::core::fbtypes::SysCmdReset>(nullptr);
}

inline void FinishSysCmdResetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::SysCmdReset> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSysCmdResetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<motion::core::fbtypes::SysCmdReset> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<motion::core::fbtypes::SysCmdResetT> UnPackSysCmdReset(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::SysCmdResetT>(GetSysCmdReset(buf)->UnPack(res));
}

inline std::unique_ptr<motion::core::fbtypes::SysCmdResetT> UnPackSizePrefixedSysCmdReset(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<motion::core::fbtypes::SysCmdResetT>(GetSizePrefixedSysCmdReset(buf)->UnPack(res));
}

}  // namespace fbtypes
}  // namespace core
}  // namespace motion

#endif  // FLATBUFFERS_GENERATED_SYSCMDRESET_MOTION_CORE_FBTYPES_H_
